name: Auto deploy

on:
  push:
    branches: [ v4 ]

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Build Vue app
        run: npm install && npm run build

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          keep_history: true
          allow_empty_commit: false
          build_dir: dist
          commit_message: "Auto deploy from build ${{ github.sha }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
